name: docker build & test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Mount bazel cache
      uses: actions/cache@v2
      with:
        path: "~/.cache/bazel"  # See https://docs.bazel.build/versions/master/output_directories.html
        key: bazel_docker

    - name: Build Docker image
      run: docker build --tag p4-constraints .
    
    - name: Build p4-constraints
      env:
        CMD: bazel build //p4_constraints/...
      run: docker run -v $HOME/.cache/bazel:/root/.cache/bazel:Z --tty p4-constraints $CMD

    - name: Unit test
      env:
        CMD: bazel test //p4_constraints/... --test_output=errors
      run: docker run -v $HOME/.cache/bazel:/root/.cache/bazel:Z --tty p4-constraints $CMD

    - name: Gold test
      env:
        CMD: bazel test //e2e-test/... --test_output=errors
      run: docker run -v $HOME/.cache/bazel:/root/.cache/bazel:Z --tty p4-constraints $CMD

